#!/bin/bash
#======{[ GIT INIT ]}=======#
git config --global user.email "peter@never.lan"
git config --global user.name "Peter Pan"
git config --global push.default simple
#======{[ NODE INIT ]}======#
cd /home/jovyan
npm i